# Generated by Django 5.1.4 on 2026-03-30 17:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("communities", "0003_directmessage_report_message"),
        ("mapview", "0003_ingestionjob_ingestionschedule_scorerecencyconfig"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="category",
            field=models.CharField(
                choices=[
                    ("general", "General Discussion"),
                    ("maintenance", "Maintenance Issue"),
                    ("safety", "Safety Concern"),
                    ("landlord", "Landlord Issue"),
                    ("noise", "Noise Complaint"),
                    ("organizing", "Organizing/Meetup"),
                    ("question", "Question"),
                    ("resource", "Resource Sharing"),
                ],
                default="general",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="post",
            name="image",
            field=models.ImageField(
                blank=True, null=True, upload_to="community_posts/%Y/%m/"
            ),
        ),
        migrations.AddField(
            model_name="post",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="post",
            name="linked_address",
            field=models.CharField(blank=True, default="", max_length=300),
        ),
        migrations.AddField(
            model_name="post",
            name="linked_lat",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="post",
            name="linked_lng",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="post",
            name="content",
            field=models.TextField(max_length=5000),
        ),
        migrations.AlterField(
            model_name="post",
            name="title",
            field=models.CharField(max_length=200),
        ),
        migrations.CreateModel(
            name="Community",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True, default="")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "nta",
                    models.OneToOneField(
                        db_column="nta_code",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="community",
                        to="mapview.ntariskscore",
                        to_field="nta_code",
                    ),
                ),
            ],
            options={
                "verbose_name": "Community",
                "verbose_name_plural": "Communities",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="CommunityMembership",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("joined_at", models.DateTimeField(auto_now_add=True)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "community",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="members",
                        to="communities.community",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="community_memberships",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Community Membership",
                "verbose_name_plural": "Community Memberships",
                "unique_together": {("user", "community")},
            },
        ),
    ]
