# Generated by Django 6.0.2 on 2026-03-04 22:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="VerificationRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "address",
                    models.CharField(
                        help_text="Full street address of the building (e.g. 123 Main St, Apt 4B, New York, NY 10001)",
                        max_length=255,
                    ),
                ),
                ("borough", models.CharField(blank=True, default="", max_length=20)),
                ("zip_code", models.CharField(blank=True, default="", max_length=10)),
                (
                    "nta_code",
                    models.CharField(
                        blank=True, db_index=True, default="", max_length=10
                    ),
                ),
                (
                    "document_type",
                    models.CharField(
                        choices=[
                            ("lease", "Lease Agreement"),
                            ("utility_bill", "Utility Bill"),
                            ("bank_statement", "Bank Statement"),
                            ("government_mail", "Government Mail"),
                            ("other", "Other"),
                        ],
                        help_text="Type of proof-of-residency document",
                        max_length=20,
                    ),
                ),
                (
                    "document_description",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="Additional details about the document (e.g. date range, account holder name)",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending Review"),
                            ("approved", "Approved"),
                            ("rejected", "Rejected"),
                        ],
                        db_index=True,
                        default="pending",
                        max_length=10,
                    ),
                ),
                (
                    "admin_notes",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="Notes from the admin reviewer (visible to the user after review)",
                    ),
                ),
                ("reviewed_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "reviewed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="reviewed_verifications",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="verification_requests",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Verification Request",
                "verbose_name_plural": "Verification Requests",
                "ordering": ["-created_at"],
            },
        ),
    ]
