# Generated by Django 6.0.2 on 2026-03-04 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_verificationrequest"),
    ]

    operations = [
        migrations.AddField(
            model_name="verificationrequest",
            name="document",
            field=models.FileField(
                blank=True,
                help_text="Upload proof-of-residency document (PDF, JPG, or PNG — max 10 MB)",
                null=True,
                upload_to="verification_documents/%Y/%m/",
            ),
        ),
    ]
