# Generated by Django 5.1.4 on 2026-03-30 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_verificationrequest_document"),
    ]

    operations = [
        migrations.AddField(
            model_name="verificationrequest",
            name="latitude",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="verificationrequest",
            name="longitude",
            field=models.FloatField(blank=True, null=True),
        ),
    ]
