# Generated by Django 6.0.3 on 2026-04-29 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0004_verificationrequest_latitude_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="verificationrequest",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending Review"),
                    ("approved", "Approved"),
                    ("rejected", "Rejected"),
                    ("withdrawn", "Withdrawn"),
                ],
                db_index=True,
                default="pending",
                max_length=10,
            ),
        ),
    ]
