# Generated by Django 6.0.2 on 2026-03-03 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Complaint311",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "unique_key",
                    models.CharField(db_index=True, max_length=20, unique=True),
                ),
                ("created_date", models.DateTimeField(blank=True, null=True)),
                ("closed_date", models.DateTimeField(blank=True, null=True)),
                ("agency", models.CharField(blank=True, default="", max_length=20)),
                ("complaint_type", models.CharField(db_index=True, max_length=100)),
                (
                    "descriptor",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                (
                    "location_type",
                    models.CharField(blank=True, default="", max_length=100),
                ),
                (
                    "incident_address",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                (
                    "incident_zip",
                    models.CharField(blank=True, default="", max_length=10),
                ),
                ("borough", models.CharField(blank=True, default="", max_length=20)),
                ("status", models.CharField(blank=True, default="", max_length=50)),
                ("resolution_description", models.TextField(blank=True, default="")),
                (
                    "bbl",
                    models.CharField(
                        blank=True, db_index=True, default="", max_length=15
                    ),
                ),
                (
                    "nta_code",
                    models.CharField(
                        blank=True, db_index=True, default="", max_length=10
                    ),
                ),
                ("latitude", models.FloatField(blank=True, null=True)),
                ("longitude", models.FloatField(blank=True, null=True)),
                ("ingested_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "311 Complaint",
                "verbose_name_plural": "311 Complaints",
                "ordering": ["-created_date"],
            },
        ),
        migrations.CreateModel(
            name="HPDViolation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("violation_id", models.IntegerField(db_index=True, unique=True)),
                (
                    "bbl",
                    models.CharField(
                        blank=True, db_index=True, default="", max_length=15
                    ),
                ),
                ("borough", models.CharField(blank=True, default="", max_length=20)),
                (
                    "house_number",
                    models.CharField(blank=True, default="", max_length=20),
                ),
                (
                    "street_name",
                    models.CharField(blank=True, default="", max_length=100),
                ),
                ("apartment", models.CharField(blank=True, default="", max_length=20)),
                ("zip_code", models.CharField(blank=True, default="", max_length=10)),
                ("violation_class", models.CharField(db_index=True, max_length=5)),
                ("inspection_date", models.DateField(blank=True, null=True)),
                ("approved_date", models.DateField(blank=True, null=True)),
                ("nov_description", models.TextField(blank=True, default="")),
                ("nov_issued_date", models.DateField(blank=True, null=True)),
                (
                    "current_status",
                    models.CharField(blank=True, default="", max_length=50),
                ),
                ("current_status_id", models.IntegerField(blank=True, null=True)),
                (
                    "violation_status",
                    models.CharField(blank=True, default="", max_length=50),
                ),
                ("violation_status_date", models.DateField(blank=True, null=True)),
                (
                    "nta_code",
                    models.CharField(
                        blank=True, db_index=True, default="", max_length=10
                    ),
                ),
                ("latitude", models.FloatField(blank=True, null=True)),
                ("longitude", models.FloatField(blank=True, null=True)),
                ("ingested_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "HPD Violation",
                "verbose_name_plural": "HPD Violations",
                "ordering": ["-inspection_date"],
            },
        ),
        migrations.CreateModel(
            name="NTARiskScore",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nta_code",
                    models.CharField(db_index=True, max_length=10, unique=True),
                ),
                ("nta_name", models.CharField(max_length=100)),
                ("borough", models.CharField(max_length=20)),
                ("total_violations", models.IntegerField(default=0)),
                ("total_complaints", models.IntegerField(default=0)),
                ("class_a_violations", models.IntegerField(default=0)),
                ("class_b_violations", models.IntegerField(default=0)),
                ("class_c_violations", models.IntegerField(default=0)),
                ("risk_score", models.FloatField(default=5.0)),
                ("top_complaint_types", models.JSONField(default=list)),
                ("summary", models.TextField(blank=True, default="")),
                ("last_updated", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "NTA Risk Score",
                "verbose_name_plural": "NTA Risk Scores",
                "ordering": ["risk_score"],
            },
        ),
    ]
