# Generated by Django 6.0.3 on 2026-03-23 01:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mapview", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ScoreThreshold",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="e.g. 'High Risk', 'Medium Risk', 'Low Risk'",
                        max_length=50,
                    ),
                ),
                (
                    "color",
                    models.CharField(
                        help_text="Hex color code (e.g., #dc2626)", max_length=20
                    ),
                ),
                (
                    "max_score",
                    models.FloatField(
                        help_text="Maximum score for this color. Ordered lowest to highest."
                    ),
                ),
            ],
            options={
                "verbose_name": "Score Threshold",
                "verbose_name_plural": "Score Thresholds",
                "ordering": ["max_score"],
            },
        ),
    ]
