# Generated by Django 5.1.4 on 2026-03-30 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mapview", "0002_scorethreshold"),
    ]

    operations = [
        migrations.CreateModel(
            name="IngestionJob",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("running", "Running"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                        ],
                        db_index=True,
                        default="pending",
                        max_length=20,
                    ),
                ),
                (
                    "trigger_type",
                    models.CharField(
                        choices=[("manual", "Manual"), ("scheduled", "Scheduled")],
                        default="manual",
                        max_length=20,
                    ),
                ),
                ("requested_limit", models.IntegerField(default=10000)),
                (
                    "sources",
                    models.CharField(
                        choices=[
                            ("both", "Both"),
                            ("hpd_only", "HPD Only"),
                            ("311_only", "311 Only"),
                        ],
                        default="both",
                        max_length=50,
                    ),
                ),
                (
                    "current_step",
                    models.CharField(blank=True, default="", max_length=100),
                ),
                ("records_fetched", models.IntegerField(default=0)),
                ("records_target", models.IntegerField(default=0)),
                ("current_batch", models.IntegerField(default=0)),
                ("total_batches", models.IntegerField(default=0)),
                ("hpd_created", models.IntegerField(default=0)),
                ("hpd_updated", models.IntegerField(default=0)),
                ("complaints_created", models.IntegerField(default=0)),
                ("complaints_updated", models.IntegerField(default=0)),
                ("neighborhoods_scored", models.IntegerField(default=0)),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("error_message", models.TextField(blank=True, default="")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Ingestion Job",
                "verbose_name_plural": "Ingestion Jobs",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="IngestionSchedule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_enabled", models.BooleanField(default=False)),
                ("interval_value", models.IntegerField(default=7)),
                (
                    "interval_unit",
                    models.CharField(
                        choices=[("hours", "Hours"), ("days", "Days")],
                        default="days",
                        max_length=10,
                    ),
                ),
                (
                    "run_time",
                    models.TimeField(
                        default="03:00", help_text="Scheduled run time in UTC"
                    ),
                ),
                ("record_limit", models.IntegerField(default=10000)),
                (
                    "sources",
                    models.CharField(
                        choices=[
                            ("both", "Both"),
                            ("hpd_only", "HPD Only"),
                            ("311_only", "311 Only"),
                        ],
                        default="both",
                        max_length=50,
                    ),
                ),
                ("last_run_at", models.DateTimeField(blank=True, null=True)),
                ("next_run_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "Ingestion Schedule",
                "verbose_name_plural": "Ingestion Schedules",
            },
        ),
        migrations.CreateModel(
            name="ScoreRecencyConfig",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "recency_window",
                    models.CharField(
                        choices=[
                            ("1m", "Last 1 month"),
                            ("3m", "Last 3 months"),
                            ("6m", "Last 6 months"),
                            ("1y", "Last 1 year"),
                            ("2y", "Last 2 years"),
                            ("all", "All time"),
                        ],
                        default="all",
                        max_length=5,
                    ),
                ),
                ("last_recomputed_at", models.DateTimeField(blank=True, null=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Score Recency Config",
                "verbose_name_plural": "Score Recency Configs",
            },
        ),
    ]
