# Generated by Django 5.1.4 on 2026-04-04 23:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mapview", "0003_ingestionjob_ingestionschedule_scorerecencyconfig"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Notification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "notification_type",
                    models.CharField(
                        choices=[
                            ("risk_change", "Risk Score Change"),
                            ("ingestion", "Ingestion Complete"),
                        ],
                        default="risk_change",
                        max_length=20,
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("message", models.TextField()),
                ("nta_code", models.CharField(blank=True, default="", max_length=10)),
                ("is_read", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notifications",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Notification",
                "verbose_name_plural": "Notifications",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="AreaSubscription",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nta_code", models.CharField(db_index=True, max_length=10)),
                ("nta_name", models.CharField(blank=True, default="", max_length=100)),
                (
                    "delivery_method",
                    models.CharField(
                        choices=[
                            ("email", "Email"),
                            ("in_app", "In-App"),
                            ("both", "Both"),
                        ],
                        default="in_app",
                        max_length=10,
                    ),
                ),
                (
                    "threshold",
                    models.FloatField(
                        default=0.5, help_text="Minimum score change to trigger alert"
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="area_subscriptions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Area Subscription",
                "verbose_name_plural": "Area Subscriptions",
                "unique_together": {("user", "nta_code")},
            },
        ),
        migrations.CreateModel(
            name="RiskScoreHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nta_code", models.CharField(db_index=True, max_length=10)),
                ("nta_name", models.CharField(max_length=100)),
                ("risk_score", models.FloatField()),
                ("previous_score", models.FloatField(blank=True, null=True)),
                ("score_delta", models.FloatField(default=0.0)),
                ("total_violations", models.IntegerField(default=0)),
                ("total_complaints", models.IntegerField(default=0)),
                ("recorded_at", models.DateTimeField(auto_now_add=True)),
                (
                    "ingestion_job",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="score_history",
                        to="mapview.ingestionjob",
                    ),
                ),
            ],
            options={
                "verbose_name": "Risk Score History",
                "verbose_name_plural": "Risk Score Histories",
                "ordering": ["-recorded_at"],
                "indexes": [
                    models.Index(
                        fields=["nta_code", "-recorded_at"],
                        name="mapview_ris_nta_cod_53cda0_idx",
                    )
                ],
            },
        ),
    ]
